'use strict';

module.exports = {
  up: async (queryInterface, _Sequelize) => {
    await queryInterface.bulkInsert('matches',
     [
      {
        home_team: 'Palmeiras',
        away_team: 'Cuiabá',
        home_score: 2,
        away_score: 1,
        date: '15-04-2023',
        stadium_id: 17,
        round_id: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'América-MG',
        away_team: 'Fluminense',
        home_score: 0,
        away_score: 3,
        date: '15-04-2023',
        stadium_id: 1,
        round_id: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Botafogo',
        away_team: 'São Paulo',
        home_score: 2,
        away_score: 1,
        date: '15-04-2023',
        stadium_id: 5,
        round_id: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Bragantino',
        away_team: 'Bahia',
        home_score: 2,
        away_score: 1,
        date: '15-04-2023',
        stadium_id: 6,
        round_id: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Athlético-PR',
        away_team: 'Goiás',
        home_score: 2,
        away_score: 0,
        date: '15-04-2023',
        stadium_id: 3,
        round_id: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Fortaleza',
        away_team: 'Internacional',
        home_score: 1,
        away_score: 1,
        date: '15-04-2023',
        stadium_id: 12,
        round_id: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Atlético-MG',
        away_team: 'Internacional',
        home_score: 1,
        away_score: 2,
        date: '15-04-2023',
        stadium_id: 9,
        round_id: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Corinthians',
        away_team: 'Cruzeiro',
        home_score: 2,
        away_score: 1,
        date: '16-04-2023',
        stadium_id: 7,
        round_id: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Flamengo',
        away_team: 'Coritiba',
        home_score: 3,
        away_score: 0,
        date: '16-04-2023',
        stadium_id: 11,
        round_id: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Grêmio',
        away_team: 'Santos',
        home_score: 1,
        away_score: 0,
        date: '16-04-2023',
        stadium_id: 15,
        round_id: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Fluminense',
        away_team: 'Athlético-PR',
        home_score: 2,
        away_score: 0,
        date: '22-04-2023',
        stadium_id: 11,
        round_id: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'São Paulo',
        away_team: 'América-MG',
        home_score: 3,
        away_score: 0,
        date: '22-04-2023',
        stadium_id: 19,
        round_id: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Cuiabá',
        away_team: 'Bragantino',
        home_score: 1,
        away_score: 1,
        date: '22-04-2023',
        stadium_id: 10,
        round_id: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Cruzeiro',
        away_team: 'Grêmio',
        home_score: 1,
        away_score: 0,
        date: '22-04-2023',
        stadium_id: 1,
        round_id: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Internacional',
        away_team: 'Flamengo',
        home_score: 2,
        away_score: 1,
        date: '23-04-2023',
        stadium_id: 16,
        round_id: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Santos',
        away_team: 'América-MG',
        home_score: 0,
        away_score: 0,
        date: '23-04-2023',
        stadium_id: 18,
        round_id: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Vasco',
        away_team: 'Palmeiras',
        home_score: 2,
        away_score: 2,
        date: '23-04-2023',
        stadium_id: 11,
        round_id: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Coritiba',
        away_team: 'Fortaleza',
        home_score: 0,
        away_score: 3,
        date: '23-04-2023',
        stadium_id: 8,
        round_id: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Goiás',
        away_team: 'Corinthians',
        home_score: 3,
        away_score: 1,
        date: '23-04-2023',
        stadium_id: 13,
        round_id: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Bahia',
        away_team: 'Botafogo',
        home_score: 1,
        away_score: 2,
        date: '24-04-2023',
        stadium_id: 4,
        round_id: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Fortaleza',
        away_team: 'Fluminense',
        home_score: 4,
        away_score: 2,
        date: '29-04-2023',
        stadium_id: 12,
        round_id: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Coritiba',
        away_team: 'São Paulo',
        home_score: 1,
        away_score: 1,
        date: '29-04-2023',
        stadium_id: 8,
        round_id: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Palmeiras',
        away_team: 'Corinthians',
        home_score: 2,
        away_score: 1,
        date: '29-04-2023',
        stadium_id: 17,
        round_id: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Santos',
        away_team: 'America-MG',
        home_score: 3,
        away_score: 2,
        date: '29-04-2023',
        stadium_id: 18,
        round_id: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Bragantino',
        away_team: 'Cruzeiro',
        home_score: 0,
        away_score: 3,
        date: '29-04-2023',
        stadium_id: 6,
        round_id: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Atlético-MG',
        away_team: 'Athlético-PR',
        home_score: 2,
        away_score: 1,
        date: '29-04-2023',
        stadium_id: 1,
        round_id: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Flamengo',
        away_team: 'Botafogo',
        home_score: 2,
        away_score: 3,
        date: '30-04-2023',
        stadium_id: 11,
        round_id: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Cuiabá',
        away_team: 'Grêmio',
        home_score: 1,
        away_score: 2,
        date: '30-04-2023',
        stadium_id: 10,
        round_id: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Internacional',
        away_team: 'Goiás',
        home_score: 1,
        away_score: 0,
        date: '30-04-2023',
        stadium_id: 16,
        round_id: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Vasco',
        away_team: 'Bahia',
        home_score: 0,
        away_score: 1,
        date: '01-05-2023',
        stadium_id: 20,
        round_id: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Cruzeiro',
        away_team: 'Santos',
        home_score: 2,
        away_score: 1,
        date: '06-05-2023',
        stadium_id: 1,
        round_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Fluminense',
        away_team: 'Vasco',
        home_score: 1,
        away_score: 1,
        date: '06-05-2023',
        stadium_id: 11,
        round_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'América-MG',
        away_team: 'Cuiabá',
        home_score: 1,
        away_score: 2,
        date: '07-05-2023',
        stadium_id: 1,
        round_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Bahia',
        away_team: 'Coritiba',
        home_score: 3,
        away_score: 1,
        date: '07-05-2023',
        stadium_id: 4,
        round_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'São Paulo',
        away_team: 'Internacional',
        home_score: 2,
        away_score: 0,
        date: '07-05-2023',
        stadium_id: 19,
        round_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Athlético-PR',
        away_team: 'Flamengo',
        home_score: 2,
        away_score: 1,
        date: '07-05-2023',
        stadium_id: 3,
        round_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Grêmio',
        away_team: 'Bragantino',
        home_score: 3,
        away_score: 3,
        date: '07-05-2023',
        stadium_id: 14,
        round_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Botafogo',
        away_team: 'Atlético-MG',
        home_score: 2,
        away_score: 0,
        date: '07-05-2023',
        stadium_id: 5,
        round_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Goiás',
        away_team: 'Palmeiras',
        home_score: 0,
        away_score: 5,
        date: '07-05-2023',
        stadium_id: 13,
        round_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Corinthians',
        away_team: 'Fortaleza',
        home_score: 1,
        away_score: 1,
        date: '08-05-2023',
        stadium_id: 7,
        round_id: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Internacional',
        away_team: 'Athlético-PR',
        home_score: 0,
        away_score: 2,
        date: '10-05-2023',
        stadium_id: 16,
        round_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Santos',
        away_team: 'Bahia',
        home_score: 3,
        away_score: 0,
        date: '10-05-2023',
        stadium_id: 18,
        round_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Bragantino',
        away_team: 'América-MG',
        home_score: 2,
        away_score: 2,
        date: '10-05-2023',
        stadium_id: 6,
        round_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Cuiabá',
        away_team: 'Atlético-MG',
        home_score: 0,
        away_score: 4,
        date: '10-05-2023',
        stadium_id: 10,
        round_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Flamengo',
        away_team: 'Goiás',
        home_score: 2,
        away_score: 0,
        date: '10-05-2023',
        stadium_id: 11,
        round_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Cruzeiro',
        away_team: 'Fluminense',
        home_score: 0,
        away_score: 2,
        date: '10-05-2023',
        stadium_id: 9,
        round_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Palmeiras',
        away_team: 'Grêmio',
        home_score: 4,
        away_score: 1,
        date: '10-05-2023',
        stadium_id: 17,
        round_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Coritiba',
        away_team: 'Vasco',
        home_score: 1,
        away_score: 1,
        date: '11-05-2023',
        stadium_id: 8,
        round_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Botafogo',
        away_team: 'Corinthians',
        home_score: 3,
        away_score: 0,
        date: '11-05-2023',
        stadium_id: 5,
        round_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Fortaleza',
        away_team: 'São Paulo',
        home_score: 0,
        away_score: 0,
        date: '11-05-2023',
        stadium_id: 12,
        round_id: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Bahia',
        away_team: 'Flamengo',
        home_score: 2,
        away_score: 3,
        date: '13-05-2023',
        stadium_id: 4,
        round_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Fluminense',
        away_team: 'Cuiabá',
        home_score: 2,
        away_score: 0,
        date: '13-05-2023',
        stadium_id: 11,
        round_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Palmeiras',
        away_team: 'Bragantino',
        home_score: 1,
        away_score: 1,
        date: '13-05-2023',
        stadium_id: 17,
        round_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Atlético-MG',
        away_team: 'Internacional',
        home_score: 2,
        away_score: 0,
        date: '13-05-2023',
        stadium_id: 9,
        round_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Grêmio',
        away_team: 'Fortaleza',
        home_score: 0,
        away_score: 0,
        date: '14-05-2023',
        stadium_id: 14,
        round_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Vasco',
        away_team: 'Santos',
        home_score: 0,
        away_score: 1,
        date: '14-05-2023',
        stadium_id: 20,
        round_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Corinthians',
        away_team: 'São Paulo',
        home_score: 1,
        away_score: 1,
        date: '14-05-2023',
        stadium_id: 7,
        round_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Athlético-PR',
        away_team: 'Coritiba',
        home_score: 3,
        away_score: 2,
        date: '14-05-2023',
        stadium_id: 3,
        round_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'Goiás',
        away_team: 'Botafogo',
        home_score: 2,
        away_score: 1,
        date: '14-05-2023',
        stadium_id: 13,
        round_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        home_team: 'América-MG',
        away_team: 'Cruzeiro',
        home_score: 0,
        away_score: 4,
        date: '14-05-2023',
        stadium_id: 1,
        round_id: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
    ],
    {},
    );
  },

  down: async (queryInterface, _Sequelize) => {
    await queryInterface.bulkDelete('matches', null, {});
  }
};